### ISSUE TITLE
Broker crashes when receiving a 400 Bad Request or 410 Gone from a subscriber

### ISSUE THREAD

**Issue by bvandewe** [neuroglia-io/cloud-streams#36] opened 2023-03-29 22:34 UTC
**Describe the bug**
The broker service crashes when it received a status code 400 Bad Request or a 410 Gone from a subscriber.

The 400 was sent by the event-viewer tool, and the 410 by the pubhook. 

**To Reproduce**
Steps to reproduce the behavior: have a subscriber send a 4xx status code...

Subscriber's definition: 

```yaml
apiVersion: cloud-streams.io/v1
kind: Subscription
metadata:
  name: event-viewer
  labels:
    cloud-streams.io/network-id: network-1
spec:
  stream:
    offset: 1
  subscriber:
    uri: http://event-viewer/events/pub
    rateLimit: 5

```

```text
2023-03-30 00:16:13 info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
2023-03-30 00:16:13       Start processing HTTP request POST http://event-viewer/events/pub
2023-03-30 00:16:13 info: System.Net.Http.HttpClient.Default.ClientHandler[100]
2023-03-30 00:16:13       Sending HTTP request POST http://event-viewer/events/pub
2023-03-30 00:16:13 info: System.Net.Http.HttpClient.Default.ClientHandler[101]
2023-03-30 00:16:13       Received HTTP response headers after 5.3618ms - 400
2023-03-30 00:16:13 info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
2023-03-30 00:16:13       End processing HTTP request after 5.5772ms - 400
2023-03-30 00:16:13 fail: CloudStreams.Broker.Application.Services.SubscriptionHandler[0]
2023-03-30 00:16:13       An error occured while watching updates to the handled subscription 'CloudStreams.Core.Data.Models.Subscription': System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
2023-03-30 00:16:13          at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
2023-03-30 00:16:13          at CloudStreams.Broker.Application.Services.SubscriptionHandler.DispatchAsync(CloudEvent e, Boolean retryIfUnavailable, Boolean catchUpWhenAvailable) in /src/src/broker/application/Services/SubscriptionHandler.cs:line 316
2023-03-30 00:16:13          at CloudStreams.Broker.Application.Services.SubscriptionHandler.CatchUpAsync() in /src/src/broker/application/Services/SubscriptionHandler.cs:line 366
2023-03-30 00:16:13          at CloudStreams.Broker.Application.Services.SubscriptionHandler.InitializeCloudEventStreamAsync() in /src/src/broker/application/Services/SubscriptionHandler.cs:line 172
2023-03-30 00:16:13          at CloudStreams.Broker.Application.Services.SubscriptionHandler.OnSubscriptionUpdatedAsync(Subscription subscription) in /src/src/broker/application/Services/SubscriptionHandler.cs:line 409
2023-03-30 00:16:18 info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
2023-03-30 00:16:18       Start processing HTTP request POST http://event-viewer/events/pub
2023-03-30 00:16:18 info: System.Net.Http.HttpClient.Default.ClientHandler[100]
2023-03-30 00:16:18       Sending HTTP request POST http://event-viewer/events/pub
2023-03-30 00:16:18 info: System.Net.Http.HttpClient.Default.ClientHandler[101]
2023-03-30 00:16:18       Received HTTP response headers after 1.7772ms - 400
2023-03-30 00:16:18 info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
2023-03-30 00:16:18       End processing HTTP request after 1.9189ms - 400
2023-03-30 00:16:18 fail: Microsoft.Extensions.Hosting.Internal.Host[9]
2023-03-30 00:16:18       BackgroundService failed
2023-03-30 00:16:18       System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
2023-03-30 00:16:18          at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionHandler.DispatchAsync(CloudEvent e, Boolean retryIfUnavailable, Boolean catchUpWhenAvailable) in /src/src/broker/application/Services/SubscriptionHandler.cs:line 316
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionHandler.<>c__DisplayClass66_0.<<RetryDispatchAsync>b__2>d.MoveNext() in /src/src/broker/application/Services/SubscriptionHandler.cs:line 338
2023-03-30 00:16:18       --- End of stack trace from previous location ---
2023-03-30 00:16:18          at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
2023-03-30 00:16:18       --- End of stack trace from previous location ---
2023-03-30 00:16:18          at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.<>c__DisplayClass8_0`1.<<ImplementationAsync>b__0>d.MoveNext()
2023-03-30 00:16:18       --- End of stack trace from previous location ---
2023-03-30 00:16:18          at Polly.CircuitBreaker.AsyncCircuitBreakerEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
2023-03-30 00:16:18          at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
2023-03-30 00:16:18          at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
2023-03-30 00:16:18          at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass4_0.<<ImplementationAsync>b__0>d.MoveNext()
2023-03-30 00:16:18       --- End of stack trace from previous location ---
2023-03-30 00:16:18          at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
2023-03-30 00:16:18       --- End of stack trace from previous location ---
2023-03-30 00:16:18          at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
2023-03-30 00:16:18          at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
2023-03-30 00:16:18          at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy innerPolicy)
2023-03-30 00:16:18          at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionHandler.RetryDispatchAsync(CloudEvent e, Boolean catchUpWhenAvailable) in /src/src/broker/application/Services/SubscriptionHandler.cs:line 337
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionHandler.DispatchAsync(CloudEvent e, Boolean retryIfUnavailable, Boolean catchUpWhenAvailable) in /src/src/broker/application/Services/SubscriptionHandler.cs:line 316
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionHandler.CatchUpAsync() in /src/src/broker/application/Services/SubscriptionHandler.cs:line 366
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionHandler.InitializeCloudEventStreamAsync() in /src/src/broker/application/Services/SubscriptionHandler.cs:line 172
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionManager.OnSubscriptionCreatedAsync(Subscription subscription) in /src/src/broker/application/Services/SubscriptionManager.cs:line 94
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionManager.ExecuteAsync(CancellationToken stoppingToken) in /src/src/broker/application/Services/SubscriptionManager.cs:line 72
2023-03-30 00:16:18          at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2023-03-30 00:16:18 crit: Microsoft.Extensions.Hosting.Internal.Host[10]
2023-03-30 00:16:18       The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
2023-03-30 00:16:18       System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
2023-03-30 00:16:18          at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionHandler.DispatchAsync(CloudEvent e, Boolean retryIfUnavailable, Boolean catchUpWhenAvailable) in /src/src/broker/application/Services/SubscriptionHandler.cs:line 316
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionHandler.<>c__DisplayClass66_0.<<RetryDispatchAsync>b__2>d.MoveNext() in /src/src/broker/application/Services/SubscriptionHandler.cs:line 338
2023-03-30 00:16:18       --- End of stack trace from previous location ---
2023-03-30 00:16:18          at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
2023-03-30 00:16:18       --- End of stack trace from previous location ---
2023-03-30 00:16:18          at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.<>c__DisplayClass8_0`1.<<ImplementationAsync>b__0>d.MoveNext()
2023-03-30 00:16:18       --- End of stack trace from previous location ---
2023-03-30 00:16:18          at Polly.CircuitBreaker.AsyncCircuitBreakerEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
2023-03-30 00:16:18          at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
2023-03-30 00:16:18          at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
2023-03-30 00:16:18          at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass4_0.<<ImplementationAsync>b__0>d.MoveNext()
2023-03-30 00:16:18       --- End of stack trace from previous location ---
2023-03-30 00:16:18          at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
2023-03-30 00:16:18       --- End of stack trace from previous location ---
2023-03-30 00:16:18          at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
2023-03-30 00:16:18          at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
2023-03-30 00:16:18          at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy innerPolicy)
2023-03-30 00:16:18          at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionHandler.RetryDispatchAsync(CloudEvent e, Boolean catchUpWhenAvailable) in /src/src/broker/application/Services/SubscriptionHandler.cs:line 337
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionHandler.DispatchAsync(CloudEvent e, Boolean retryIfUnavailable, Boolean catchUpWhenAvailable) in /src/src/broker/application/Services/SubscriptionHandler.cs:line 316
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionHandler.CatchUpAsync() in /src/src/broker/application/Services/SubscriptionHandler.cs:line 366
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionHandler.InitializeCloudEventStreamAsync() in /src/src/broker/application/Services/SubscriptionHandler.cs:line 172
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionManager.OnSubscriptionCreatedAsync(Subscription subscription) in /src/src/broker/application/Services/SubscriptionManager.cs:line 94
2023-03-30 00:16:18          at CloudStreams.Broker.Application.Services.SubscriptionManager.ExecuteAsync(CancellationToken stoppingToken) in /src/src/broker/application/Services/SubscriptionManager.cs:line 72
2023-03-30 00:16:18          at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2023-03-30 00:16:18 info: Microsoft.Hosting.Lifetime[0]
2023-03-30 00:16:18       Application is shutting down...
```

```text

2023-03-30 00:27:47 info: System.Net.Http.HttpClient.Default.ClientHandler[100]
2023-03-30 00:27:47       Sending HTTP request POST https://pubhook.certs.cloud/56cbc1f7-6452-4e8d-b529-a6418402557b
2023-03-30 00:27:47 info: System.Net.Http.HttpClient.Default.ClientHandler[101]
2023-03-30 00:27:47       Received HTTP response headers after 194.4815ms - 410
2023-03-30 00:27:47 info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
2023-03-30 00:27:47       End processing HTTP request after 194.7049ms - 410
2023-03-30 00:27:47 fail: Microsoft.Extensions.Hosting.Internal.Host[9]
2023-03-30 00:27:47       BackgroundService failed
2023-03-30 00:27:47       System.Net.Http.HttpRequestException: Response status code does not indicate success: 410 (Gone).
2023-03-30 00:27:47          at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
2023-03-30 00:27:47          at CloudStreams.Broker.Application.Services.SubscriptionHandler.DispatchAsync(CloudEvent e, Boolean retryIfUnavailable, Boolean catchUpWhenAvailable) in /src/src/broker/application/Services/SubscriptionHandler.cs:line 316
2023-03-30 00:27:47          at CloudStreams.Broker.Application.Services.SubscriptionHandler.CatchUpAsync() in /src/src/broker/application/Services/SubscriptionHandler.cs:line 366
2023-03-30 00:27:47          at CloudStreams.Broker.Application.Services.SubscriptionHandler.InitializeCloudEventStreamAsync() in /src/src/broker/application/Services/SubscriptionHandler.cs:line 172
2023-03-30 00:27:47          at CloudStreams.Broker.Application.Services.SubscriptionManager.OnSubscriptionCreatedAsync(Subscription subscription) in /src/src/broker/application/Services/SubscriptionManager.cs:line 94
2023-03-30 00:27:47          at CloudStreams.Broker.Application.Services.SubscriptionManager.ExecuteAsync(CancellationToken stoppingToken) in /src/src/broker/application/Services/SubscriptionManager.cs:line 72
2023-03-30 00:27:47          at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2023-03-30 00:27:47 crit: Microsoft.Extensions.Hosting.Internal.Host[10]
2023-03-30 00:27:47       The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
2023-03-30 00:27:47       System.Net.Http.HttpRequestException: Response status code does not indicate success: 410 (Gone).
2023-03-30 00:27:47          at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
2023-03-30 00:27:47          at CloudStreams.Broker.Application.Services.SubscriptionHandler.DispatchAsync(CloudEvent e, Boolean retryIfUnavailable, Boolean catchUpWhenAvailable) in /src/src/broker/application/Services/SubscriptionHandler.cs:line 316
2023-03-30 00:27:47          at CloudStreams.Broker.Application.Services.SubscriptionHandler.CatchUpAsync() in /src/src/broker/application/Services/SubscriptionHandler.cs:line 366
2023-03-30 00:27:47          at CloudStreams.Broker.Application.Services.SubscriptionHandler.InitializeCloudEventStreamAsync() in /src/src/broker/application/Services/SubscriptionHandler.cs:line 172
2023-03-30 00:27:47          at CloudStreams.Broker.Application.Services.SubscriptionManager.OnSubscriptionCreatedAsync(Subscription subscription) in /src/src/broker/application/Services/SubscriptionManager.cs:line 94
2023-03-30 00:27:47          at CloudStreams.Broker.Application.Services.SubscriptionManager.ExecuteAsync(CancellationToken stoppingToken) in /src/src/broker/application/Services/SubscriptionManager.cs:line 72
2023-03-30 00:27:47          at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2023-03-30 00:27:47 info: Microsoft.Hosting.Lifetime[0]
2023-03-30 00:27:47       Application is shutting down...
```

**Expected behavior**
Broker shouldnt crash when receiving a 4xx status code, or any other status code.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS - Docker Desktop Kubernetes
 - Browser [e.g. chrome, safari] Chrome

**Comment by cdavernas** [comment] 2023-03-30 11:11
Closing as this bug is caused by the same reasons than #28, which is addressed in next release.

Thanks for reporting though ❤️

**Closed by cdavernas** 2023-03-30 11:11 UTC
Labels: bug, duplicate
